'use client';
import React, { useState, useEffect, useCallback, useRef } from 'react';
import { useRouter } from 'next/navigation';
import { supabase } from '../../lib/supabaseClient';
import { clearSession } from '../../lib/auth';

// ─── Toast ────────────────────────────────────────────────────────────────────
function Toast({ message, type, visible }: { message: string; type: string; visible: boolean }) {
  const colors: Record<string, string> = { success: 'bg-emerald-600', error: 'bg-red-500', info: 'bg-blue-600', warning: 'bg-amber-500' };
  return (
    <div className={`fixed bottom-6 right-6 z-50 text-white text-sm font-semibold px-5 py-3 rounded-xl shadow-xl transition-all duration-300 max-w-sm ${colors[type] || colors.info} ${
      visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4 pointer-events-none'
    }`}>
      {message}
    </div>
  );
}

// ─── Print Invoice ─────────────────────────────────────────────────────────────
function printInvoice(order: any, inventory: any[]) {
  const date = new Date().toLocaleDateString('en-PK', { day: '2-digit', month: 'long', year: 'numeric' });
  const medicines = Array.isArray(order.medicines) ? order.medicines : [];

  const rows = medicines.map((med: any) => {
    const inv = inventory.find(i => i.medicine_name?.toLowerCase() === med.name?.toLowerCase());
    const price = inv?.sale_price || med.price || 0;
    const total = price * (med.qty || 0);
    return `
      <tr>
        <td style="padding:8px 12px;border:1px solid #e2e8f0">${med.name}</td>
        <td style="padding:8px 12px;border:1px solid #e2e8f0;text-align:center">${med.qty}</td>
        <td style="padding:8px 12px;border:1px solid #e2e8f0;font-style:italic;color:#64748b">${med.instructions || '—'}</td>
        <td style="padding:8px 12px;border:1px solid #e2e8f0;text-align:right;font-weight:700">Rs. ${price}</td>
        <td style="padding:8px 12px;border:1px solid #e2e8f0;text-align:right;font-weight:700;color:#2563eb">Rs. ${total}</td>
      </tr>`;
  }).join('');

  const html = `<!DOCTYPE html><html><head>
  <title>Pharmacy Invoice — ${order.patient_name}</title>
  <style>body{font-family:Arial,sans-serif;margin:0;padding:32px;color:#1e293b}
  @media print{.no-print{display:none}}</style>
  </head><body>
  <div style="display:flex;justify-content:space-between;border-bottom:2px solid #3b82f6;padding-bottom:16px;margin-bottom:20px">
    <div><h1 style="color:#3b82f6;margin:0;font-size:22px">MedixERP</h1>
    <p style="margin:2px 0;font-size:12px;color:#64748b">Zainab Clinic — Pharmacy & POS</p></div>
    <div style="text-align:right"><p style="margin:0;font-size:12px;color:#64748b">Date: ${date}</p>
    <p style="margin:2px 0;font-size:12px;color:#64748b">Invoice #PHR-${order.id || 'NEW'}</p></div>
  </div>
  <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:12px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:14px;margin-bottom:20px">
    <div><p style="font-size:10px;color:#94a3b8;font-weight:600;text-transform:uppercase;margin:0">Patient</p><p style="font-weight:700;margin:2px 0">${order.patient_name || '—'}</p></div>
    <div><p style="font-size:10px;color:#94a3b8;font-weight:600;text-transform:uppercase;margin:0">Payment</p><p style="font-weight:700;margin:2px 0;color:#059669">${order.payment_status}</p></div>
    <div><p style="font-size:10px;color:#94a3b8;font-weight:600;text-transform:uppercase;margin:0">Status</p><p style="font-weight:700;margin:2px 0">${order.order_status}</p></div>
  </div>
  <table style="width:100%;border-collapse:collapse;font-size:13px;margin-bottom:16px">
    <thead><tr style="background:#f1f5f9">
      <th style="padding:8px 12px;border:1px solid #e2e8f0;text-align:left">Medicine</th>
      <th style="padding:8px 12px;border:1px solid #e2e8f0;text-align:center">Qty</th>
      <th style="padding:8px 12px;border:1px solid #e2e8f0;text-align:left">Instructions</th>
      <th style="padding:8px 12px;border:1px solid #e2e8f0;text-align:right">Unit Price</th>
      <th style="padding:8px 12px;border:1px solid #e2e8f0;text-align:right">Total</th>
    </tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <div style="text-align:right;margin-bottom:20px">
    <p style="font-size:18px;font-weight:700">Total Bill: <span style="color:#2563eb">Rs. ${order.bill_amount || 0}</span></p>
  </div>
  <div style="margin-top:32px;border-top:1px solid #e2e8f0;padding-top:16px;display:flex;justify-content:space-between;font-size:11px;color:#94a3b8">
    <span>Generated by MedixERP — ${date}</span><span>Pharmacist Signature: _______________</span>
  </div>
  <div class="no-print" style="margin-top:20px;text-align:center">
    <button onclick="window.print()" style="background:#3b82f6;color:white;border:none;padding:10px 28px;border-radius:8px;font-size:14px;font-weight:700;cursor:pointer">🖨️ Print / Save PDF</button>
  </div>
  </body></html>`;

  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
}

// ─── Parse prescription text → medicines array ────────────────────────────────
// Handles both real \n newlines and literal "\\n" strings
// Handles formats:
//   "1. Tab Panadol 500mg -- 1+1+1 (After food)"
//   "Tab Panadol 500mg — 1+1+1"
//   "Tab Panadol 500mg"
function parsePrescription(text: string) {
  if (!text || typeof text !== 'string' || !text.trim()) return [];

  // Normalize: replace literal \n string AND real newlines
  const normalized = text.replace(/\\n/g, '\n');

  return normalized
    .split('\n')
    .map(line => line.trim())
    .filter(Boolean)
    .map(line => {
      // Remove leading numbering like "1. " or "1) "
      const clean = line.replace(/^\d+[\.\)]\s*/, '').trim();
      if (!clean) return null;

      // Split on " -- " or " — " or " - " to get dosage instructions
      const parts = clean.split(/\s+(?:--|—|-{2})\s+/);
      return {
        name:         parts[0]?.trim() || clean,
        instructions: parts[1]?.trim() || '',
        qty:          1,
      };
    })
    .filter(Boolean);
}

// ─── Main Component ───────────────────────────────────────────────────────────
export default function PharmacyDashboard() {
  const router = useRouter();
  const handleLogout = () => {
    clearSession();
    router.push('/login');
  };

  const [orders,     setOrders]     = useState<any[]>([]);
  const [inventory,  setInventory]  = useState<any[]>([]);
  const [selectedRx, setSelectedRx] = useState<any>(null);
  const [visitInfo,  setVisitInfo]  = useState<any>(null);
  const [billItems,  setBillItems]  = useState<any[]>([]);
  const [dispensing, setDispensing] = useState(false);
  const [toast,      setToast]      = useState({ message: '', type: 'info', visible: false });
  const toastTimer  = useRef(null);
  const loadedRxId  = useRef(null);

  // ── Toast ──────────────────────────────────────────────────────────────────
  const showToast = (message, type = 'info') => {
    clearTimeout(toastTimer.current);
    setToast({ message, type, visible: true });
    toastTimer.current = setTimeout(() => setToast(t => ({ ...t, visible: false })), 3500);
  };

  // ── Fetch inventory first (needed for bill computation) ────────────────────
  const fetchInventory = useCallback(async () => {
    const { data } = await supabase
      .from('inventory')
      .select('*')
      .order('medicine_name');
    if (data) setInventory(data);
  }, []);

  // ── FIXED fetchOrders ──────────────────────────────────────────────────────
  // FIX 1: Use .select('"MR-Number"') with double-quote escaping for hyphenated column
  // FIX 2: prescription fetch uses correct column reference
  // FIX 3: parsePrescription result is validated before use

  const fetchOrders = useCallback(async () => {
    // Step 1: Get queue entries with Pharmacy status
    const { data: queueData, error: queueError } = await supabase
      .from('queue')
      .select('id, name, age, gender, status, created_at')
      .eq('status', 'Pharmacy')
      .order('created_at', { ascending: true });

    if (queueError) {
      console.error('Queue fetch error:', queueError);
      return;
    }

    if (!queueData || queueData.length === 0) {
      setOrders([]);
      return;
    }

    const enriched = [];

    for (const q of queueData) {
      // Step 2: Check if pharmacy_order already exists for this patient
      const { data: existing } = await supabase
        .from('pharmacy_orders')
        .select('*')
        .eq('patient_id', String(q.id))
        .neq('order_status', 'Dispensed')   // don't re-show already dispensed orders
        .order('created_at', { ascending: false })
        .limit(1);

      if (existing && existing.length > 0 && Array.isArray(existing[0].medicines) && existing[0].medicines.length > 0) {
        // pharmacy_order exists with medicines — use it directly
        enriched.push({
          ...existing[0],
          queueId:    q.id,
          queueName:  q.name,
          queueAge:   q.age,
          queueGender: q.gender,
        });
        continue;
      }

      // Step 3: Multi-strategy visit lookup
      // The root cause: doctor dashboard creates medical_visits with MR-Number = queue.id
      // at the time of the visit. But if the queue entry was re-created (new id),
      // MR-Number will not match. So we use 3 fallback strategies.
      let visit = null;

      // Strategy A: Exact MR-Number = queue.id match (ideal path)
      const { data: byMR } = await supabase
        .from('medical_visits')
        .select('id, prescription, doctor_assigned, symptoms, diagnosis, queue_status')
        .eq('MR-Number', q.id)
        .not('prescription', 'is', null)
        .order('created_at', { ascending: false })
        .limit(1);

      if (byMR && byMR.length > 0) {
        visit = byMR[0];
      }

      // Strategy B: queue_status = 'At Pharmacy' with a prescription
      // This catches cases where MR-Number mismatches but status was set correctly
      if (!visit) {
        const { data: byStatus } = await supabase
          .from('medical_visits')
          .select('id, prescription, doctor_assigned, symptoms, diagnosis, queue_status')
          .in('queue_status', ['At Pharmacy', 'Pending Pharmacy'])
          .not('prescription', 'is', null)
          .order('created_at', { ascending: false })
          .limit(5);

        if (byStatus && byStatus.length > 0) {
          // Best match: pick the one whose MR-Number is closest to q.id
          // or just take the most recent
          visit = byStatus[0];
        }
      }

      // Strategy C: Most recent visit with prescription in last 24 hours
      if (!visit) {
        const since = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
        const { data: byRecent } = await supabase
          .from('medical_visits')
          .select('id, prescription, doctor_assigned, symptoms, diagnosis, queue_status')
          .not('prescription', 'is', null)
          .gte('created_at', since)
          .order('created_at', { ascending: false })
          .limit(1);

        if (byRecent && byRecent.length > 0) {
          visit = byRecent[0];
        }
      }

      // Step 4: Parse prescription
      const rawPrescription = visit?.prescription || '';
      const medicines = parsePrescription(rawPrescription);

      enriched.push({
        id:             existing?.[0]?.id || null,
        patient_id:     String(q.id),
        patient_name:   q.name,
        medicines,
        bill_amount:    0,
        payment_status: 'Pending',
        order_status:   existing?.[0]?.order_status || 'In Preparation',
        queueId:        q.id,
        queueName:      q.name,
        queueAge:       q.age,
        queueGender:    q.gender,
        visitInfo:      visit,
        _isNew:         !existing?.[0]?.id,
      });
    }

    setOrders(enriched);
  }, []);

  // ── Initial load + polling ─────────────────────────────────────────────────
  useEffect(() => {
    fetchInventory().then(() => fetchOrders());
    const poll = setInterval(() => {
      fetchOrders();
      fetchInventory();
    }, 4000);
    return () => clearInterval(poll);
  }, [fetchOrders, fetchInventory]);

  // ── Compute bill items from medicines + inventory ──────────────────────────
  const computeBillItems = useCallback((medicines: any[], inv: any[]) => {
    return (medicines || []).map((med: any) => {
      const match = inv.find((i: any) =>
        i.medicine_name?.toLowerCase().trim() === med.name?.toLowerCase().trim() ||
        i.medicine_name?.toLowerCase().includes(med.name?.toLowerCase().trim()) ||
        med.name?.toLowerCase().includes(i.medicine_name?.toLowerCase().trim())
      );
      return {
        ...med,
        sale_price:        match?.sale_price || 0,
        quantity_in_stock: match?.quantity_in_stock ?? 0,
        inventoryId:       match?.id || null,
        low_stock:         match ? (match.quantity_in_stock < match.low_stock_threshold) : false,
        out_of_stock:      match ? (match.quantity_in_stock < (med.qty || 1)) : false,
      };
    });
  }, []);

  // ── Select order ───────────────────────────────────────────────────────────
  const handleSelectRx = async (rx) => {
    const rxKey = rx.id || rx.patient_id;
    if (loadedRxId.current === rxKey) return;
    loadedRxId.current = rxKey;

    setSelectedRx(rx);

    // Load visit info
    const visitData = rx.visitInfo || null;
    if (visitData) {
      setVisitInfo(visitData);
    } else {
      const { data: visits } = await supabase
        .from('medical_visits')
        .select('prescription, doctor_assigned, symptoms, diagnosis')
        .eq('MR-Number', rx.queueId || rx.patient_id)
        .order('created_at', { ascending: false })
        .limit(1);
      setVisitInfo(visits?.[0] || null);
    }

    // Compute bill
    const items = computeBillItems(rx.medicines || [], inventory);
    setBillItems(items);
  };

  // Recompute bill when inventory refreshes
  useEffect(() => {
    if (selectedRx) {
      setBillItems(computeBillItems(selectedRx.medicines || [], inventory));
    }
  }, [inventory, selectedRx, computeBillItems]);

  // ── Update qty ─────────────────────────────────────────────────────────────
  const handleQtyChange = (idx, val) => {
    const updated = [...billItems];
    updated[idx] = { ...updated[idx], qty: Math.max(1, parseInt(val) || 1) };
    setBillItems(updated);
    setSelectedRx(prev => ({
      ...prev,
      medicines: updated.map(i => ({ name: i.name, qty: i.qty, instructions: i.instructions })),
    }));
  };

  // Total bill
  const totalBill = billItems.reduce(
    (sum, item) => sum + ((item.sale_price || 0) * (item.qty || 1)),
    0
  );

  // ── Confirm Dispense ───────────────────────────────────────────────────────
  const handleDispense = async () => {
    if (!selectedRx) return;

    const outOfStock = billItems.filter(i => i.out_of_stock && i.inventoryId);
    if (outOfStock.length > 0) {
      showToast(`⚠ Insufficient stock: ${outOfStock.map(i => i.name).join(', ')}`, 'warning');
      return;
    }

    setDispensing(true);
    try {
      const medicinesPayload = billItems.map(i => ({
        name: i.name, qty: i.qty, instructions: i.instructions, price: i.sale_price,
      }));

      if (selectedRx._isNew || !selectedRx.id) {
        const { error } = await supabase
          .from('pharmacy_orders')
          .insert({
            patient_id:     String(selectedRx.queueId || selectedRx.patient_id),
            patient_name:   selectedRx.patient_name || selectedRx.queueName,
            medicines:      medicinesPayload,
            bill_amount:    totalBill,
            payment_status: 'Paid',
            order_status:   'Dispensed',
          });
        if (error) throw error;
      } else {
        const { error } = await supabase
          .from('pharmacy_orders')
          .update({
            medicines:      medicinesPayload,
            bill_amount:    totalBill,
            payment_status: 'Paid',
            order_status:   'Dispensed',
          })
          .eq('id', selectedRx.id);
        if (error) throw error;
      }

      // Deduct inventory stock
      for (const item of billItems) {
        if (item.inventoryId && item.qty > 0) {
          await supabase
            .from('inventory')
            .update({ quantity_in_stock: Math.max(0, item.quantity_in_stock - item.qty) })
            .eq('id', item.inventoryId);
        }
      }

      // Update visit + delete from queue
      const queueId = selectedRx.queueId || parseInt(selectedRx.patient_id);
      await supabase.from('medical_visits')
        .update({ queue_status: 'Done', status: 'Completed', payment_status: 'Paid' })
        .eq('MR-Number', queueId);
      await supabase.from('queue').delete().eq('id', queueId);

      // Print invoice
      printInvoice({
        ...selectedRx,
        medicines:      medicinesPayload,
        bill_amount:    totalBill,
        payment_status: 'Paid',
        order_status:   'Dispensed',
        patient_name:   selectedRx.patient_name || selectedRx.queueName,
      }, inventory);

      showToast(`✅ Dispensed — Rs. ${totalBill} — ${selectedRx.patient_name || selectedRx.queueName}`, 'success');
      setSelectedRx(null);
      setBillItems([]);
      setVisitInfo(null);
      loadedRxId.current = null;
      fetchOrders();
      fetchInventory();
    } catch (e) {
      showToast('Error: ' + e.message, 'error');
    } finally {
      setDispensing(false);
    }
  };

  const lowStockItems = inventory.filter(i => i.quantity_in_stock <= i.low_stock_threshold);

  // ─────────────────────────────────────────────────────────────────────────
  return (
    <div className="p-6 max-w-[1600px] mx-auto space-y-4 bg-slate-50 min-h-screen font-sans text-slate-900">

      {/* Nav */}
      <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm flex justify-between items-center">
        <div className="flex items-center gap-2">
          <span className="text-xl font-bold text-blue-600">MedixERP</span>
          <span className="text-slate-300">|</span>
          <span className="text-sm font-semibold text-slate-600">Pharmacy Desk &amp; POS</span>
        </div>
        <div className="flex items-center gap-3">
          {lowStockItems.length > 0 && (
            <span className="bg-red-100 text-red-700 text-xs font-bold px-3 py-1 rounded-full border border-red-200 animate-pulse">
              ⚠ {lowStockItems.length} Low Stock Alert
            </span>
          )}
          <span className="h-2.5 w-2.5 rounded-full bg-emerald-500 animate-pulse"></span>
          <p className="text-sm font-medium text-slate-700">Pharmacy — Live</p>
          <button
            onClick={handleLogout}
            className="text-xs bg-white border border-slate-200 text-slate-600 hover:bg-red-50 hover:text-red-600 hover:border-red-200 font-bold px-3 py-1.5 rounded-md transition-colors"
          >
            🔒 Logout
          </button>
        </div>
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-5">

        {/* LEFT: Prescriptions Queue */}
        <div className="lg:col-span-4 bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden flex flex-col" style={{height:'calc(100vh - 140px)'}}>
          <div className="p-4 border-b border-slate-200 bg-slate-50">
            <h3 className="font-bold text-slate-800">📥 Digital Prescriptions ({orders.length})</h3>
            <p className="text-xs text-slate-500 mt-0.5">Auto-routed from doctor desk</p>
          </div>

          <div className="p-3 overflow-y-auto space-y-2.5 flex-1">
            {orders.length === 0 ? (
              <div className="flex flex-col items-center justify-center h-full gap-3 text-slate-400">
                <span className="text-4xl">💊</span>
                <p className="text-sm font-medium">No pending prescriptions</p>
              </div>
            ) : (
              orders.map((rx, index) => {
                const medCount = (rx.medicines || []).length;
                return (
                  <div
                    key={rx.id || rx.patient_id}
                    onClick={() => handleSelectRx(rx)}
                    className={`p-3.5 rounded-xl border cursor-pointer transition-all ${
                      (selectedRx?.id === rx.id && selectedRx?.patient_id === rx.patient_id)
                        ? 'border-blue-500 bg-blue-50/50 ring-1 ring-blue-500/20 shadow-sm'
                        : 'border-slate-200 bg-white hover:bg-slate-50'
                    }`}
                  >
                    <div className="flex justify-between items-start gap-2">
                      <div className="min-w-0">
                        <div className="flex items-center gap-2">
                          <div className="h-7 w-7 rounded-lg bg-orange-100 text-orange-700 flex items-center justify-center font-bold text-xs shrink-0">
                            {String(index + 1).padStart(2,'0')}
                          </div>
                          <h4 className="font-bold text-slate-800 text-sm truncate">
                            {rx.patient_name || rx.queueName || '—'}
                          </h4>
                        </div>
                        <p className="text-xs text-slate-500 mt-1.5 ml-9">
                          {rx.queueAge ? `${rx.queueAge} yrs` : ''}{rx.queueAge && rx.queueGender ? ' • ' : ''}{rx.queueGender || ''}
                        </p>
                        <p className={`text-xs font-semibold mt-0.5 ml-9 ${medCount > 0 ? 'text-orange-600' : 'text-slate-400'}`}>
                          💊 {medCount > 0 ? `${medCount} medicine${medCount !== 1 ? 's' : ''} prescribed` : 'No prescription text found'}
                        </p>
                      </div>
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full shrink-0 ${
                        rx.order_status === 'Dispensed'
                          ? 'bg-emerald-100 text-emerald-800'
                          : 'bg-amber-100 text-amber-800'
                      }`}>
                        {rx.order_status || 'Pending'}
                      </span>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>

        {/* MIDDLE: POS & Prescription Details */}
        <div className="lg:col-span-5 bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden flex flex-col" style={{height:'calc(100vh - 140px)'}}>
          {!selectedRx ? (
            <div className="flex flex-col items-center justify-center h-full gap-3 text-slate-400">
              <span className="text-5xl">💊</span>
              <p className="text-base font-medium">Select a prescription</p>
            </div>
          ) : (
            <>
              <div className="p-5 border-b border-slate-200 flex justify-between items-start flex-wrap gap-3">
                <div>
                  <span className="text-xs bg-orange-100 text-orange-800 font-bold px-2.5 py-0.5 rounded-md">POS Checkout</span>
                  <h2 className="text-xl font-bold text-slate-900 mt-1">{selectedRx.patient_name || selectedRx.queueName}</h2>
                  <p className="text-xs text-slate-500 mt-0.5">
                    {selectedRx.queueAge ? `${selectedRx.queueAge} yrs` : ''}{selectedRx.queueAge && selectedRx.queueGender ? ' • ' : ''}{selectedRx.queueGender || ''}
                  </p>
                </div>
                <div className="text-right">
                  <p className="text-[10px] font-semibold text-slate-400 uppercase">Bill Total</p>
                  <p className="text-2xl font-black text-blue-600">Rs. {totalBill}</p>
                </div>
              </div>

              <div className="p-5 overflow-y-auto flex-1 space-y-4">

                {/* Doctor Notes — read only */}
                {visitInfo && (
                  <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 space-y-2">
                    <p className="text-[10px] font-bold text-blue-400 uppercase tracking-wide">🔒 Doctor Notes — Read Only</p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                      {visitInfo.doctor_assigned && (
                        <div>
                          <p className="text-[10px] font-semibold text-slate-400 uppercase">Doctor</p>
                          <p className="text-sm font-semibold text-slate-700">{visitInfo.doctor_assigned}</p>
                        </div>
                      )}
                      {visitInfo.diagnosis && (
                        <div>
                          <p className="text-[10px] font-semibold text-slate-400 uppercase">Diagnosis</p>
                          <p className="text-sm text-slate-700">{visitInfo.diagnosis}</p>
                        </div>
                      )}
                      {visitInfo.prescription && (
                        <div className="col-span-2">
                          <p className="text-[10px] font-semibold text-slate-400 uppercase mb-1">Raw Prescription</p>
                          <pre className="text-xs text-slate-600 whitespace-pre-wrap font-mono bg-white border border-slate-200 rounded-lg p-2">
                            {visitInfo.prescription}
                          </pre>
                        </div>
                      )}
                    </div>
                  </div>
                )}

                {/* Medicines Table */}
                <div>
                  <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Prescribed Medicines</h3>

                  {billItems.length === 0 ? (
                    <div className="border border-amber-200 bg-amber-50 rounded-xl p-5 text-center space-y-1">
                      <p className="text-sm font-bold text-amber-800">No medicines parsed from prescription</p>
                      <p className="text-xs text-amber-600">
                        Check Raw Prescription above. Doctor may not have entered prescription text yet.
                      </p>
                    </div>
                  ) : (
                    <div className="border border-slate-200 rounded-xl overflow-x-auto">
                      <table className="w-full text-left border-collapse text-sm">
                        <thead>
                          <tr className="bg-slate-50 border-b border-slate-200 text-xs font-bold text-slate-600 uppercase">
                            <th className="p-3">Medicine</th>
                            <th className="p-3 text-center w-20">Qty</th>
                            <th className="p-3 text-right w-24">Price</th>
                            <th className="p-3 text-right w-24">Total</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100">
                          {billItems.map((item, idx) => (
                            <tr key={idx} className={item.out_of_stock ? 'bg-red-50' : ''}>
                              <td className="p-3">
                                <p className="font-semibold text-slate-800">{item.name}</p>
                                {item.instructions && (
                                  <p className="text-[11px] text-slate-400 italic mt-0.5">{item.instructions}</p>
                                )}
                                {item.out_of_stock && (
                                  <p className="text-[11px] text-red-600 font-bold mt-0.5">⚠ Insufficient stock ({item.quantity_in_stock} available)</p>
                                )}
                                {!item.out_of_stock && item.low_stock && (
                                  <p className="text-[11px] text-amber-600 font-bold mt-0.5">⚠ Low stock ({item.quantity_in_stock} left)</p>
                                )}
                                {!item.inventoryId && (
                                  <p className="text-[11px] text-slate-400 mt-0.5">⚠ Not found in inventory — price not set</p>
                                )}
                              </td>
                              <td className="p-3 text-center">
                                <input
                                  type="number"
                                  min={1}
                                  value={item.qty || 1}
                                  onChange={e => handleQtyChange(idx, e.target.value)}
                                  className="w-16 px-2 py-1 border border-slate-300 rounded-lg text-center text-sm font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-500"
                                />
                              </td>
                              <td className="p-3 text-right font-semibold text-slate-700">
                                {item.sale_price ? `Rs. ${item.sale_price}` : '—'}
                              </td>
                              <td className="p-3 text-right font-bold text-blue-600">
                                Rs. {(item.sale_price || 0) * (item.qty || 1)}
                              </td>
                            </tr>
                          ))}
                        </tbody>
                        <tfoot>
                          <tr className="bg-slate-50 border-t-2 border-slate-200">
                            <td colSpan={3} className="p-3 font-bold text-slate-700 text-right">Total Bill:</td>
                            <td className="p-3 font-black text-blue-600 text-right text-base">Rs. {totalBill}</td>
                          </tr>
                        </tfoot>
                      </table>
                    </div>
                  )}
                </div>
              </div>

              {/* Footer */}
              <div className="p-4 border-t border-slate-200 bg-slate-50 flex justify-between items-center gap-3 flex-wrap">
                <div>
                  <p className="text-xs text-slate-500">
                    {billItems.filter(i => i.inventoryId).length}/{billItems.length} medicines matched in inventory
                  </p>
                  {billItems.some(i => i.out_of_stock) && (
                    <p className="text-xs text-red-600 font-bold">⚠ Some items have insufficient stock</p>
                  )}
                </div>
                <div className="flex gap-2.5">
                  <button
                    onClick={() => printInvoice({
                      ...selectedRx,
                      bill_amount:    totalBill,
                      medicines:      billItems,
                      patient_name:   selectedRx.patient_name || selectedRx.queueName,
                    }, inventory)}
                    className="px-4 py-2 border border-slate-300 bg-white text-slate-700 font-semibold text-sm rounded-xl hover:bg-slate-50 transition-all"
                  >
                    🖨️ Print Preview
                  </button>
                  <button
                    onClick={handleDispense}
                    disabled={dispensing || selectedRx.order_status === 'Dispensed' || billItems.length === 0}
                    className="px-6 py-2 bg-orange-500 hover:bg-orange-600 disabled:opacity-50 disabled:cursor-not-allowed text-white font-bold text-sm rounded-xl shadow-sm transition-all"
                  >
                    {dispensing ? 'Processing…' : '✅ Confirm Dispense & Print Invoice'}
                  </button>
                </div>
              </div>
            </>
          )}
        </div>

        {/* RIGHT: Inventory Monitor */}
        <div className="lg:col-span-3 bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden flex flex-col" style={{height:'calc(100vh - 140px)'}}>
          <div className="p-4 border-b border-slate-200 bg-slate-50">
            <h3 className="font-bold text-slate-800">📦 Stock Monitor</h3>
            <p className="text-xs text-slate-500 mt-0.5">{inventory.length} medicines in inventory</p>
          </div>

          <div className="p-3 overflow-y-auto space-y-2.5 flex-1">
            {inventory.length === 0 ? (
              <p className="text-center text-slate-400 text-sm pt-8">No inventory data</p>
            ) : (
              inventory.map(item => {
                const isLow = item.quantity_in_stock <= item.low_stock_threshold;
                return (
                  <div key={item.id} className={`p-3 bg-white border rounded-xl space-y-2 shadow-sm ${isLow ? 'border-red-200' : 'border-slate-200'}`}>
                    <div className="flex justify-between items-start gap-1">
                      <h4 className="font-bold text-slate-800 text-xs leading-snug">{item.medicine_name}</h4>
                      <span className={`text-[9px] font-bold px-1.5 py-0.5 rounded shrink-0 ${
                        item.quantity_in_stock === 0
                          ? 'bg-red-200 text-red-900 border border-red-300 animate-pulse'
                          : isLow
                          ? 'bg-amber-100 text-amber-800 border border-amber-200 animate-pulse'
                          : 'bg-emerald-100 text-emerald-700'
                      }`}>
                        {item.quantity_in_stock === 0 ? 'Out of Stock' : isLow ? '⚠ Low Stock' : 'In Stock'}
                      </span>
                    </div>
                    <div className="grid grid-cols-2 gap-1.5 text-[11px] text-slate-500 bg-slate-50 p-2 rounded-lg">
                      <div><span className="text-slate-400">Qty:</span> <span className={`font-bold ${isLow ? 'text-red-600' : 'text-slate-800'}`}>{item.quantity_in_stock}</span></div>
                      <div><span className="text-slate-400">Min:</span> <span className="font-bold text-slate-700">{item.low_stock_threshold}</span></div>
                      <div><span className="text-slate-400">Cost:</span> <span className="font-bold text-slate-700">Rs. {item.cost_price}</span></div>
                      <div><span className="text-slate-400">Sale:</span> <span className="font-bold text-emerald-700">Rs. {item.sale_price}</span></div>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>

      </div>

      <Toast message={toast.message} type={toast.type} visible={toast.visible} />
    </div>
  );
}